allowBuilds:
  "@tailwindcss/oxide": true
  cos-js-sdk-v5: true
  esbuild: true
  musae: true
minimumReleaseAgeExclude:
  - "@aiszlab/relax"
  - musae
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - musae
